// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: constant.proto

package constant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataBase int32

const (
	// User
	DataBase_User DataBase = 0
)

// Enum value maps for DataBase.
var (
	DataBase_name = map[int32]string{
		0: "User",
	}
	DataBase_value = map[string]int32{
		"User": 0,
	}
)

func (x DataBase) Enum() *DataBase {
	p := new(DataBase)
	*p = x
	return p
}

func (x DataBase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataBase) Descriptor() protoreflect.EnumDescriptor {
	return file_constant_proto_enumTypes[0].Descriptor()
}

func (DataBase) Type() protoreflect.EnumType {
	return &file_constant_proto_enumTypes[0]
}

func (x DataBase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataBase.Descriptor instead.
func (DataBase) EnumDescriptor() ([]byte, []int) {
	return file_constant_proto_rawDescGZIP(), []int{0}
}

var File_constant_proto protoreflect.FileDescriptor

var file_constant_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2a, 0x14, 0x0a, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x10, 0x00,
	0x42, 0x25, 0x5a, 0x23, 0x62, 0x73, 0x64, 0x62, 0x2d, 0x6b, 0x69, 0x74, 0x2f, 0x63, 0x6f, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x3b, 0x63,
	0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_constant_proto_rawDescOnce sync.Once
	file_constant_proto_rawDescData = file_constant_proto_rawDesc
)

func file_constant_proto_rawDescGZIP() []byte {
	file_constant_proto_rawDescOnce.Do(func() {
		file_constant_proto_rawDescData = protoimpl.X.CompressGZIP(file_constant_proto_rawDescData)
	})
	return file_constant_proto_rawDescData
}

var file_constant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_constant_proto_goTypes = []any{
	(DataBase)(0), // 0: constant.DataBase
}
var file_constant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_constant_proto_init() }
func file_constant_proto_init() {
	if File_constant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_constant_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constant_proto_goTypes,
		DependencyIndexes: file_constant_proto_depIdxs,
		EnumInfos:         file_constant_proto_enumTypes,
	}.Build()
	File_constant_proto = out.File
	file_constant_proto_rawDesc = nil
	file_constant_proto_goTypes = nil
	file_constant_proto_depIdxs = nil
}
